### ISSUE TITLE
locating megacli breaks

### ISSUE THREAD

**Issue by niclan** [onnozweers/Nagios-plugins#13]
Hi,

Line 40 of check_megaraid fails if the which commands fail (all of them fail for me).  This works for me:

```shell
MEGACLI=`which megacli || which MegaCli64 || echo /opt/MegaRAID/MegaCli/MegaCli64`
```

**Comment by onnozweers** [comment]
Thanks! Fixed:
https://github.com/onnozweers/Nagios-plugins/commit/4d09df0f5e1e41b39d3f02e4d7aed3b3fd181e75
